### ISSUE TITLE
Please add aarch64 version FreeBSD 13

### ISSUE THREAD

**Issue by ivan-volnov** [vmactions/freebsd-vm#18]
Hello!

Arm is extremely trending nowadays.
aarch64 is now Tier 1 support in FreeBSD 13.

Please add such vm.

https://download.freebsd.org/ftp/releases/VM-IMAGES/13.0-RELEASE/aarch64/Latest/

**Comment by Neilpang** [comment]
I don't find a way to emulate ARM64 on x86.

**Comment by ivan-volnov** [comment]
But Github Actions has arm64 runners

**Comment by ivan-volnov** [comment]
Please have a look for instance this:
https://github.com/ivan-volnov/keybr/runs/2427605016

**Comment by dentarg** [comment]
>But Github Actions has arm64 runners

Since when?

**Comment by ivan-volnov** [comment]
Yep, you are right. I see now. It hasn't yet

**Comment by neilpang** [comment]
it's already supported https://github.com/vmactions/freebsd-vm
