### ISSUE TITLE
The setup of the VM seems to run forever

### ISSUE THREAD

**Issue by GuillaumeGomez** [vmactions/freebsd-vm#22]
I'm not sure if this comes from this repository or github actions more generally, but since a few days, the VM takes forever to setup and never ends (as you can see here: https://github.com/GuillaumeGomez/sysinfo/pull/492). Any idea what's going on by any chance?

**Comment by Neilpang** [comment]
use the latest version.

**Comment by GuillaumeGomez** [comment]
Isn't 0.1.4 the latest version?

**Comment by Neilpang** [comment]
it's working for me: https://github.com/acmesh-official/acme.sh/runs/2652178116?check_suite_focus=true

show me your log.

**Comment by GuillaumeGomez** [comment]
There is no log, that's what I don't understand. You can see it there: https://github.com/GuillaumeGomez/sysinfo/pull/492/checks?check_run_id=2655838097

**Comment by Neilpang** [comment]
it's a GitHub bug. sometimes the console log is not captured .
please re-run it .

**Comment by Neilpang** [comment]
@GuillaumeGomez 
It seems the log is out:
https://github.com/GuillaumeGomez/sysinfo/pull/492/checks?check_run_id=2655838097

**Comment by Neilpang** [comment]
you can use this VM to debug:
https://github.com/vmactions/shell-freebsd

**Comment by GuillaumeGomez** [comment]
Actually it's coming from rustup apparently: https://github.com/rust-lang/rustup/issues/2629

Sorry for the noise and thanks a lot for the help!
