### ISSUE TITLE
Please add an option to avoid the rsync back to the host

### ISSUE THREAD

**Issue by sylvestre** [vmactions/freebsd-vm#30]
Currently, if I understood correctly, freebsd-vm is doing an rsync from mac => freebsd
and, at the end of the build, freebsd => mac

When it is used just to run testsuites, some users might not need to get the files back.
An option to disable this behavior would be amazing.

thanks!

**Comment by Neilpang** [comment]
you can use `sync: sshfs`  prevent from copying code.

**Comment by sylvestre** [comment]
@Neilpang this one fails with:
```

% env FUSE_DEV_NAME=/dev/fuse0 sshfs -o idmap=user \
       username@example.org:
% mount_fusefs /dev/fuse0 /path/to/mount/point

For further options see ``sshfs -h''.
kldload: can't load fuse.ko: No such file or directory
```

see
https://github.com/uutils/coreutils/pull/2614/checks?check_run_id=3454611442

**Comment by Neilpang** [comment]
did you use the latest release?

https://github.com/vmactions/freebsd-vm/pull/20
