### ISSUE TITLE
What FreeBSD version is used?

### ISSUE THREAD

**Issue by hasufell** [vmactions/freebsd-vm#36]
I don't see which version is used and if you can switch between 12 and 13.

**Comment by trombik** [comment]
> I doubt there are how many users need this feature.

the whole point of running FreeBSD runner is to build (and release) code for supported versions of FreeBSD. 

@hasufell if macOS runner supports nested virtualization, which I did not know before finding this GitHub action, it should be possible to run `vagrant` and `virtualbox`. looking at the code in this repo, it looks to me that the way it implements is not versatile. i ran `vagrant` on travis-ci long before they stopped free-tier for opensource projects. that way, you can not only choose FreeBSD versions, but also use whatever VM images you need. i'm using cirrus-ci for my projects now, but it has its own quirks.

**Comment by hasufell** [comment]
> > I doubt there are how many users need this feature.
> 
> the whole point of running FreeBSD runner is to build (and release) code for supported versions of FreeBSD. 
> 

Exactly. It doesn't help me knowing my code compiles for *some* freebsd version. I want to release for the lagest 2 major versions at least... or for the previous one, because there are compat packages.

Just supporting the latest doesn't really work well.

**Comment by hasufell** [comment]
Excellent
