### ISSUE TITLE
"vboxmanage: command not found" running freebsd-vm action on macos-latest

### ISSUE THREAD

**Issue by dvrogozh** [vmactions/freebsd-vm#38]
```
/bin/chmod 700 /Users/runner/.ssh
/usr/bin/sudo vboxmanage import /Users/runner/work/_actions/vmactions/freebsd-vm/v0.1.5/freebsd-13.0.ova
sudo: vboxmanage: command not found
Error: The process '/usr/bin/sudo' failed with exit code 1
```

I've noticed this issue in our CI which I tried to overcome by switching to the latest action (v0.1.5). This did not help for the reason that I was running on 'macos-latest' instead of 'macos-10.15'. I eventually overcame it on my side starting to use 'macos-10.15', but you might be interested in looking why some 'macos-latest' start to signify macos 11.6.1 which miss 'vboxmanage'.

See: https://github.com/intel/libva/pull/556
Job failed: https://github.com/intel/libva/runs/4452520572 (that's with macos-latest, before I switched to macos-10.15)
Jon passed: https://github.com/intel/libva/runs/4453434425 (that's with macos-10.15)

**Comment by drkameleon** [comment]
@dvrogozh Finally, somebody managed to spot this! I have been trying for days to see what might be going on...

Although it's not a definitive solution, it certainly solves the issue.

Thanks for posting it! 😉
