### ISSUE TITLE
The action is also compatible with macos-12 runners

### ISSUE THREAD

**Issue by mayeut** [vmactions/freebsd-vm#50]
The documentation states:
> The `runs-on: macos-10.15` must be `macos-10.15`.

Since https://github.com/actions/virtual-environments/pull/5594, `macos-12` is also supported.
This PR was a follow-up on `macos-10.15` deprecation notice: https://github.com/actions/virtual-environments/issues/5583

Here's a sample of this action working properly on `macos-12`: https://github.com/mayeut/psutil/runs/6698397720?check_suite_focus=true

**Comment by Neilpang** [comment]
Thank you so much.  but  macos-12 is beta for now.
I will make a new release as soon as macos-12 is in production

**Comment by mayeut** [comment]
> Thank you so much. but macos-12 is beta for now.

Yes, this was just a heads-up. FYI, macOS-12 shall be out of BETA before macos-10.15 is removed.

**Comment by hummeltech** [comment]
> Thank you so much. but macos-12 is beta for now. I will make a new release as soon as macos-12 is in production

`macos-12` [is now generally available](https://github.blog/changelog/2022-06-13-github-actions-macos-12-for-github-hosted-runners-is-now-generally-available/)

**Comment by Neilpang** [comment]
Thanks,  the readme is updated.

**Comment by Tayevans09** [comment]
👁️‍🗨️🐥🌐
