### ISSUE TITLE
Too many logs printed

### ISSUE THREAD

**Issue by timandy** [vmactions/freebsd-vm#52]
The logs of vm loading and rsync printed more than 10000 lines.

Should a param be there to switch `debug mod` or `run mode`?

https://github.com/timandy/go-asm-demo/runs/7234166808?check_suite_focus=true

**Comment by Neilpang** [comment]
please try with the latest version:
https://github.com/vmactions/freebsd-vm/releases/tag/v0.2.1

**Comment by Neilpang** [comment]
[v0.2.1](https://github.com/vmactions/freebsd-vm/releases/tag/v0.2.1)

**Comment by timandy** [comment]
sorroy for paste a wrong link. I'll watch for a while

**Comment by timandy** [comment]
This build failed with rsync error  https://github.com/timandy/go-asm-demo/runs/7560127429?check_suite_focus=true

**Comment by Neilpang** [comment]
时间同步的错误是随机的, 后面再修.   暂时 重新运行就好了.

**Comment by timandy** [comment]
@Neilpang  The count of logs not reduced.
 https://github.com/timandy/go-asm-demo/runs/7560127017?check_suite_focus=true

Thanks for your work, you really do a good job.
