### ISSUE TITLE
Support mac arm64?

### ISSUE THREAD

**Issue by timandy** [vmactions/freebsd-vm#53]
Is it feasible to support mac arm64 in a similar way?

**Comment by Neilpang** [comment]
it seems that virtual box doesn't support  arm64 on a x86-64 host.

**Comment by timandy** [comment]
> it seems that virtual box doesn't support arm64 on a x86-64 host.

Can virtual box run in docker? [This repo]( https://github.com/uraimo/run-on-arch-action) support arm64 container on linux.

**Comment by Neilpang** [comment]
首先, virtual box 不支持 跨架构的模拟技术.  而且 virtualbox 不支持运行在arm64架构上. 所以 走virtualbox 这条路就堵死了.

你给的例子用qumu模拟硬件, 理论上是行得通的.  如果宿主机采用 linux, github 的linux 主机不支持硬件虚拟化, 所以模拟性能堪忧.
只能采用 MacOS作为宿主机.  我手头也没有intel 的Mac, 这个我并没有试过. 你可以试试.

**Comment by timandy** [comment]
感谢回复
