### ISSUE TITLE
rsync error

### ISSUE THREAD

**Issue by timandy** [vmactions/freebsd-vm#54]
rsync throw an error, is it possible to exclude some folder or files sync to vm?

The folder `_PipelineMapping`, `_actions`, `_temp` should not sync by default. Cause these files will not be used in vm, and the rsync task waste a lot of time.

![image](https://user-images.githubusercontent.com/3809541/177940684-79851913-c46a-48db-9530-0c0e917f7061.png)
https://github.com/timandy/gohack/runs/7247134254?check_suite_focus=true#step:14:1479

**Comment by Neilpang** [comment]
已经修了. 请使用 主版本 `v0` 引用最新版的 `v0.x.x` 版本
