### ISSUE TITLE
FreeBSD 13.1 support

### ISSUE THREAD

**Issue by jbeich** [vmactions/freebsd-vm#55]
According to https://www.freebsd.org/security/#sup 13.0 reaches EOL on 2022-08-31. After that [the package cluster](https://pkg-status.freebsd.org/?all=1&type=package) would upgrade 13.* builders (e.g., 130amd64) to 13.1 (e.g., 131amd64), rendering `/latest` and `/quarterly` (but not [`/release_0`](https://pkg.freebsd.org/FreeBSD:13:amd64/release_0/)) package repos unusable on 13.0 because the old kernel/libc/libthr/etc may not support features introduced by 13.1.

**Comment by Neilpang** [comment]
Thanks, I will update it soon.

**Comment by jbeich** [comment]
Thanks. Seems to work OK.
