### ISSUE TITLE
With sshfs: Hang on running cmake in the FreeBSD vm (looking for pthread.h)

### ISSUE THREAD

**Issue by SimonKagstrom** [vmactions/freebsd-vm#6]
I've tried using freebsd-vm to build a C++ project, but get a hang when cmake is run on the project. A hanged build is here:

https://github.com/SimonKagstrom/kcov/runs/1627285829?check_suite_focus=true

I aborted it after 1h. The log says:

```/usr/bin/ssh freebsd sh -c 'cd $GITHUB_WORKSPACE && exec sh'
-- The C compiler identification is Clang 10.0.1
-- The CXX compiler identification is Clang 10.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
Error: The operation was canceled.
```

And then hangs. I believe cmake tries to compile a test program when looking for pthreads.

Unfortunately,  I know almost nothing about FreeBSD, so I have no idea why it might behave like this. The same project has Linux builds for ARM/ARM64/PPC which run in qemu, and these build in around 15 minutes or so.

The branch I ran this in is here:

https://github.com/SimonKagstrom/kcov/tree/issue-345-github-actions

Edit: I found that if I enable rsync, this problem goes away, so I guess it's sshfs that's the root cause.

**Comment by Neilpang** [comment]
Good.
BTW, you can use this project to debug:  https://github.com/vmactions/shell-freebsd

**Comment by SimonKagstrom** [comment]
Thanks for the hint!

I'll close this issue, but perhaps a line should be added to the documentation about potential sshfs issues?
