### ISSUE TITLE
Using sshfs does not mount workspace in the VM

### ISSUE THREAD

**Issue by ranisalt** [vmactions/freebsd-vm#62]
I wanted to switch from rsync to sshfs because the former was erratically failing to copy files back from the VM, I suspect due to the massive amount of files (it's Node.js :shrug:)

However, I found that setting `sync: sshfs` will prevent the workspace from being accessed inside the VM: https://github.com/ranisalt/node-argon2/runs/8040898297?check_suite_focus=true

In other words, the code isn't inside the VM at all. Checking a few projects that use `vmactions/freebsd-vm` I couldn't find anything special to mount the files, so I'm not sure how to workaround.

**Comment by Neilpang** [comment]
It seems like a bug.  I'm fixing it.


>> failing to copy files back from the VM

you can define `copyback: false`  to avoid copying files back.

**Comment by Neilpang** [comment]
the bug should be fixed.  and new release 0.2.4 is released.  
if you are using the major version `v0`,  it should be just working. please just rerun your workflow.

Thanks

**Comment by ranisalt** [comment]
> you can define `copyback: false` to avoid copying files back.

I need to copy them back, just not _all_ of them. In this case, I don't want to copy the dependencies, only the built binary.

`sshfs` did work now: https://github.com/ranisalt/node-argon2/runs/8050147093 

It would also be sweet to add a filter of files, but this issue is resolved :+1:

**Comment by Neilpang** [comment]
@ranisalt you can disable the copyback, and then copy back any files by `scp`:

```
scp   -r freebsd:work/path/to/any/files   ./local/files/

```

**Comment by Neilpang** [comment]
BTW,  the file path should be the same in both the VM and the host machine:

```
scp   -r freebsd:/path/to/any/files   /path/to/any/files   
```

**Comment by ranisalt** [comment]
Amazing! Thanks for the great work.
