### ISSUE TITLE
Run prepare in sh instead of csh

### ISSUE THREAD

**Issue by FWDekker** [vmactions/freebsd-vm#66]
While writing a `prepare` script, I found that I regularly ran into issues because I make mistakes because I am not familiar with the syntax of `csh` (e.g. using environment variables, using command substitution, etc.). For the `run` part, I can use the option `usesh` to use  `sh` instead of `csh`, but there is no option to do the same for the `prepare` part.

Would it be possible to either (1) make `usesh` use `sh` for both `run` and `prepare`, or (2) add `prepareusesh` (or something similar) to use `sh` also for `prepare`?

**Comment by Neilpang** [comment]
>>  (1) make usesh use sh for both run and prepare

Seems good.  I will fix it.
