### ISSUE TITLE
FreeBSD 13.2 support

### ISSUE THREAD

**Issue by jbeich** [vmactions/freebsd-vm#69]
According to https://www.freebsd.org/security/#sup 13.1 reaches EOL on 2023-07-31. After that [the package cluster](https://pkg-status.freebsd.org/?all=1&type=package) would upgrade 13.* builders (e.g., 131amd64) to 13.2 (e.g., 132amd64), rendering `/latest` and `/quarterly` (but not [`/release_1`](https://pkg.freebsd.org/FreeBSD:13:amd64/release_1/)) package repos unusable on 13.1 because the old kernel/libc/libthr/etc may not support features introduced by 13.2.

**Comment by Neilpang** [comment]
fixed,  the default version is using 13.2 now.
