### ISSUE TITLE
Increasing the amount of RAM for the guest OS

### ISSUE THREAD

**Issue by gennaroprota** [vmactions/freebsd-vm#7]
Hi,

would it be possible to increase the amount of RAM for the guest OS? I have a test case which constructs a 1GiB string, and that causes the OS to just kill the unit test process. I'd be fine with either increasing it to something like 4GiB, or allowing the user to choose the amount via the YAML file.

Thank you so much.

**Comment by Neilpang** [comment]
I will add the ability to increase the memory in YAML

**Comment by Neilpang** [comment]
please use the new release.
There is a new option `mem` added.
https://github.com/vmactions/freebsd-vm/blob/main/README.md

**Comment by gennaroprota** [comment]
It works for me, thanks! :-)
