### ISSUE TITLE
Configurable rsync options

### ISSUE THREAD

**Issue by trombik** [vmactions/freebsd-vm#79]
I am trying to use the action to test ports with `poudriere`. I want to cache packages built and sources to make the build process faster. `poudriere` uses symlinks to manage files. When copying files from the guest VM, the `rsync` options do not keep symlinks. I need to add `--links`, or `-l`, to the options. 

Would you implement configurable rsync options?

**Comment by Neilpang** [comment]
please use `sshfs`:
```
sync: sshfs
```
