### ISSUE TITLE
Virtual machine output full of garbage strings

### ISSUE THREAD

**Issue by gennaroprota** [vmactions/freebsd-vm#8]
Hi,

I noticed that the output from the virtual machine is full of very odd strings. I've attached some screenshots. Unfortunately, I can't give much details. They just seem random.

![Screenshot1](https://user-images.githubusercontent.com/4961853/103491867-662f5080-4e27-11eb-9a70-318033294681.png)

![Screenshot2](https://user-images.githubusercontent.com/4961853/103491874-6e878b80-4e27-11eb-9792-8f901e4720e7.png)

![Screenshot3](https://user-images.githubusercontent.com/4961853/103491883-78a98a00-4e27-11eb-995f-804db3f7208f.png)

![Screenshot4](https://user-images.githubusercontent.com/4961853/103491887-7e9f6b00-4e27-11eb-8638-369bf38ef79b.png)

**Comment by Neilpang** [comment]
It's the text on the screen when booting the VM.
I will remove them from the output.

**Comment by gennaroprota** [comment]
I'm not sure we are understanding each other. In the first screenshot, there's, for instance:

> AN
> 
> a
> 
> ..
> 
> Press FiZ to select...

In the second one, there's:

> PS a ee CCC csc ee

etc. etc.

**Comment by Neilpang** [comment]
I understand.  the text was OCRed from images, so, the text is not 100% correct.

**Comment by Neilpang** [comment]
BTW:  if you need to debug issues in FreeBSD VM, you can use this project: https://github.com/vmactions/shell-freebsd

**Comment by gennaroprota** [comment]
Aha, it hadn't occurred to me that it could be OCR'd text! Thanks! And thanks for the pointer to shell-freebsd, too.

**Comment by KodrAus** [comment]
@Neilpang do you have any pointers on where to go to suppress the OCR output? I'd be happy to submit a PR but am not familiar with writing Actions myself 🙂

**Comment by Neilpang** [comment]
@KodrAus 
I think it's the output of the "pytesseract" command.

please give it a try.

https://github.com/vmactions/freebsd-vm/blob/bb7ed06ef86f3f757e52fb9b62d734f8610f44ab/index.js#L25
